---
title: "Epidemiology models simulations demo"
author: Anton Antonov
date: 2020-03-26
output: html_notebook
---

```{r}
library(EpidemiologyModels)
#devtools::load_all()
library(deSolve)
library(tidyverse)
library(ggplot2)
```

```{r}
modelSIR <- SEI2HRModel()
modelSIR
```

```{r}
times <- seq( 0, 365, 1)
```

```{r}
params <- as.list( modelSIR[["RateRules"]] )
params[ c( "contactRateISSP", "contactRateINSP", "deathRateISSP", "deathRateINSP", "sspf") ] <- c( 0.56, 0.56, 0.034, 0.02, 0.2 )
params[["contactRateINSP"]] <- function(t) { 0.56 * ifelse( 60 <= t && t <= 120, 0.35, 1 ) }
params[["contactRateISSP"]] <- function(t) { 0.56 * ifelse( 60 <= t && t <= 120, 0.35, 1 ) }
params
```


Quarantine scenario:

```{r}
modelSIR[["RateRules"]] <- as.list( modelSIR[["RateRules"]] )
modelSIR[["RateRules"]][["contactRateINSP"]] <- with( list( cr = modelSIR[["RateRules"]][["contactRateINSP"]] ), function(t) { cr * ifelse( 80 <= t && t <= 80 + 56, 0.25, 1 ) } )
modelSIR[["RateRules"]][["contactRateISSP"]] <- with( list( cr = modelSIR[["RateRules"]][["contactRateISSP"]] ), function(t) { cr * ifelse( 80 <= t && t <= 80 + 56, 0.25, 1 ) } )
```

```{r}
sol <- ode(y = modelSIR[["InitialConditions"]], times = times, func = modelSIR[["RHSFunction"]], parms = modelSIR[["RateRules"]], method = "rk4" )
hist(sol)
```

```{r}
dfSol <- as.data.frame(sol)
colnames(dfSol) <- gsub( "time", "Time", colnames(dfSol) )
head(dfSol)
```


```{r}
dfSol %>% 
  tidyr::pivot_longer( cols = colnames(dfSol)[-1], names_to = "Stock", values_to = "Value" ) %>%
  dplyr::filter( Stock %in% c( "SPt", "EPt", "INSPt", "ISSPt", "HPt", "RPt", "DIPt" ) ) %>% 
  ggplot( ) +
  geom_line( aes( x = Time, y = Value, color = Stock ) )
```



```{r}
dfSol %>% 
  tidyr::pivot_longer( cols = colnames(dfSol)[-1], names_to = "Stock", values_to = "Value" ) %>%
  dplyr::filter( Stock %in% c( "ISSPt", "HPt", "DIPt" ) ) %>% 
  ggplot( ) +
  geom_line( aes( x = Time, y = Value, color = Stock ) )
```
