---
title: "Make recommender"
output: html_notebook
---

```{r}
library(magrittr)
library(Matrix)
library(SparseMatrixRecommender)
library(SMRMon)
library(DataObfuscation)
```


Extend the banking data with an ID column:

```{r}
dfMintBubblesTransactions2 <- cbind( ID = as.character(1:nrow(dfMintBubblesTransactions)), dfMintBubblesTransactions, stringsAsFactors = TRUE )
```

This is how the data looks like:

```{r}
head(dfMintBubblesTransactions2)
```

Create are recommender:

```{r}
smrObj <- 
  SMRMonUnit() %>% 
  SMRMonCreate( data = dfMintBubblesTransactions2, itemColumnName = "ID", addTagTypesToColumnNamesQ = TRUE )
```

Show the recommender tag types:

```{r}
smrObj %>% SMRMonTakeTagTypes()
```

Recommendations by profile:

```{r, rows.print = 20}
smrObj %>% 
  SMRMonRecommendByProfile( profile = c( "Amount:5.75",  "Date:2012-11-12" ), nrecs = 20 ) %>% 
  SMRMonJoinAcross( dfMintBubblesTransactions2, by = "ID" ) %>% 
  SMRMonTakeValue
```

Classify to a "Category" value using a profile:

```{r}
smrObj %>% 
  SMRMonClassifyByProfile( tagType = "Category", profile = c( "Amount:5.75" ) ) %>% 
  SMRMonTakeValue
```

