---
title: "HIRMon core code generation"
author: Anton Antonov
date: "```r Sys.Date()```"
output: html_notebook
---

# Introduction

The code in this notebook was used to generate the core code of the `HIRMon` monad; see [1].

The R design and implementation follows the design and implementation of `HIRMon` in R, see [2].

# Code generation

Here we load the State Monad code generation package:

```{r}
library(StateMonadCodeGenerator)
```

```{r}
GenerateStateMonadCode( monadName = "HIRMon", 
                        memberNames = c(
                          "M" = "matrix", 
                          "M01" = "matrix",
                          "TagTypes" = "character",
                          "TagTypeRanges" = "data.frame",
                          "Data" = "data.frame",
                          "HubItemMatrix" = "matrix", 
                          "ItemHubMatrix" = "matrix", 
                          "BiasVector" = "numeric"
                        ), 
                        monadObjectArgumentName = "hirObj", 
                        outputFile = "HIRMon-core.R")
```


# References

[1] Anton Antonov, 
[State monad code generator](https://github.com/antononcube/R-packages/tree/master/StateMonadCodeGenerator), 
(2019),
[R-packages at GitHub](https://github.com/antononcube/R-packages).

[2] Anton Antonov, 
[Hub-Item Dynamic Ranks R package](https://github.com/antononcube/R-packages/tree/master/HubItemDynamicRanks),
(2019),
[R-packages at GitHub](https://github.com/antononcube/R-packages).
