---
title: "Hub-Item Recommender experiments"
author: Anton Antonov
date: 2020-06-17
output: html_notebook
---

```{r}
library(SparseMatrixRecommender)
library(SMRMon)
library(Matrix)
library(magrittr)
library(MathematicaVsRData)
```

```{r}
devtools::load_all()
```

# Introduction

# Load data

```{r}
load("~/R/MovieLensRecommender/data/dfMovies.rda")
load("~/R/MovieLensRecommender/data/dfRatings.rda")
load("~/R/MovieLensRecommender/data/dfMovieGenres.rda")
```

## Summaries

```{r}
Summary(dfMovies)
```

```{r}
Summary(dfRatings)
```


```{r}
Summary(dfMovieGenres)
```
# Most popular movies

```{r}
dfRatings %>% 
  dplyr::count( MovieID, sort = TRUE ) %>% 
  dplyr::inner_join( dfMovies, by = "MovieID" )
```

# Extend data

```{r}
dfMovies2 <- 
  dfMovies %>% 
  dplyr::mutate( Tag = paste0( "MovieID:", MovieID) )
dfMovies2
```

# Make Hub-Item recommender

```{r}
dfRatings[, c("MovieID", "UserID", "Rating")]
```

```{r}
hirObj <- 
  HIRMonUnit() %>% 
  HIRMonCreate( dfRatings[ , c("MovieID", "UserID", "Rating")], addTagTypesToColumnNamesQ = TRUE )
```

```{r}
dfMovies2 %>% 
  dplyr::filter( grepl( "Die", Title ) )
```

```{r}
dfRecs <- 
  hirObj %>% 
  HIRMonRecommend( profile = c( "MovieID:1036", "MovieID:1370" ), nrecs = 20, alpha = 0.9, maxSteps = 100 ) %>% 
  HIRMonTakeValue
```

```{r, rows.print = 20}
dfRecs %>% 
  dplyr::inner_join( dfMovies2, by = "Tag" )
```


