---
title: "Pareto Principle adherence examples"
author: Anton Antonov
date: 2019-03-01
output: html_notebook
---

```{r setup}
library(ParetoPrincipleAdherence)
library(RandomDataFrameGenerator)
```

# Introduction

This notebook shows examples of the adherence of different datasets to the [Pareto Principle](https://en.wikipedia.org/wiki/Pareto_principle).

## Package installation

```{r, eval=F}
devtools::install_github( "antononcube/R-packages", subdir = "ParetoPrincipleAdherence")
devtools::install_github( "antononcube/R-packages", subdir = "RandomDataFrameGenerator")
```

# Examples


## The diamonds dataset

```{r}
data("diamonds")
```

```{r}
summary(diamonds)
```

```{r}
ParetoPlotForColumns(data = diamonds, columnNames = c("carat", "cut", "color", "clarity", "price"), normalizeQ = F, scales = "free", nrow = 2 )
```

```{r}
matDiamonds <- RandomDataFrame( nrow = 200, columnNames = c("Carat", "Depth", "Table"), generators = list( function(n) {res <- rnorm(n, 1, 0.6); ifelse(res < 0.1, 0.1, res)}, function(n) rnorm(n, 10, 2), function(n) rnorm(n, 50, 20) ) )
matDiamonds <- as.matrix(matDiamonds)
head(matDiamonds)
```

```{r}
ParetoForVariables(matDiamonds)
```

```{r}
ParetoPlotForVariables( matDiamonds )
```

Here we compute the Pareto statistic for a selected column:

```{r}
qDF <- ParetoForWeightedItems( diamonds$price )
qDF %>% dplyr::filter( ParetoFraction < 0.02 )
```

Using the above result in the following plot we can see 
that ~ 30% of the diamonds correspond to 70% of the total of prices.

```{r}
ParetoFramePlot( qDF$ParetoFraction, 
                 sub = "Pareto Principle for diamond prices", 
                 xFraction = 0.3, yFraction = 0.7, showParetoTicksQ = T )
```


# References

\[1\] Anton Antonov, 
["Pareto principle adherence examples"](https://mathematicaforprediction.wordpress.com/2016/11/17/pareto-principle-adherence-examples/), 
(2016),
[MathematicaForPrediction at WordPress](https://mathematicaforprediction.wordpress.com/).
