---
title: "SMRMon workflows by natural commands"
author: Anton Antonov
date: "```r Sys.Date()```"
output: html_notebook
---

```{r}
library(SMRMon)
library(SparseMatrixRecommender)
library(Matrix)
library(magrittr)
library(ExternalParsersHookUp)
# devtools::install_github(repo = "antononcube/ConversationalAgents", subdir = "Packages/R/ExternalParsersHookUp")

rakuLocationPath <- "~/.rakubrew/shims/raku"
```

# Introduction

This notebooks demonstrates the construction of recommender workflows
using natural language commands.

# Creation

Simple creation:

```{r}
smrObj <-
  SMRMonUnit( data = dfTitanic ) %>%
  SMRMonCreate( itemColumnName = "id")
```

# Basic pipeline

```{r}
dfTitanic
```


```{r}
ToRecommenderWorkflowCode( "recommend for history id.5, id.7 and id.12", parse = F, rakuLocation = rakuLocationPath)
```

```{r}
ToRecommenderWorkflowCode( 
    "create from dfTitanic;
     recommend with history id.5=10, id.7=3; 
     join across recommendations with the data frame dfTitanic; 
     echo pipeline value",
    rakuLocation = rakuLocationPath) 
```

```{r}
dfTitanic
```

```{r}
obj <- 
  SMRMonCreate( data = dfTitanic) %>%
  SMRMonRecommend( history = c("id.5"=10, "id.7"=3)) %>%
  SMRMonJoinAcross( data = dfTitanic) %>%
  SMRMonEchoValue()
```

```{r}
smrObj = SMRMonCreate( data = dfTitanic ) 
smrObj = SMRMonRecommend( smrObj, history = c("id.5", "id.7"), removeHistoryQ = FALSE )
smrObj = SMRMonJoinAcross( smrObj, data = dfTitanic)
SMRMonTakeValue(smrObj)
```


```{r}
smrObj <-
  eval( expr = ToRecommenderWorkflowCode( 
    "create from dfTitanic;
     suggest for history id.5, id.7; 
     join across recommendations with the data frame dfTitanic; 
     echo pipeline value", rakuLocation = rakuLocationPath ) ) 
```


## By profile

```{r}
ToRecommenderWorkflowCode("suggest by profile female, died", rakuLocation = rakuLocationPath )
```

This is problematic:

```{r}
# The argument "globalWeightFunction" is used twice:
ToRecommenderWorkflowCode( 
    "create from dfTitanic; 
     apply the LSI functions IDF, None, Cosine;", rakuLocation = rakuLocationPath  )
```


```{r}
ToRecommenderWorkflowCode( 
    "create from dfTitanic; 
     apply the LSI functions inverse document frequency, term frequency, and cosine;
     recommend by profile female->3, 30->0.1; 
     extend recommendations with dfTitanic; 
     show pipeline value", 
    rakuLocation = rakuLocationPath )
```

```{r}
smrObj2 <-
  SMRMonUnit() %>% 
  eval( expr = ToRecommenderWorkflowCode( 
    "create from dfTitanic; 
     apply the LSI functions IDF, TermFrequency, Cosine;
     recommend by profile female->1, 30->0.1; 
     extend recommendations with dfTitanic; 
     show pipeline value",
    rakuLocation = rakuLocationPath ) )
```

## Profile finding


```{r}
smrObj3 <- 
  eval( ToRecommenderWorkflowCode( 
    "use recommender smrObj2; 
     compute profile for the history id.5, id.993; 
     echo pipeline value;
     find top 5 recommendations;
     extend recommendations with dfTitanic;
     echo pipeline value;",
    rakuLocation = rakuLocationPath ) )
```

## Classification

```{r}
smrObj3 <- 
  eval( ToRecommenderWorkflowCode( 
    "use recommender smrObj2; 
     recommend by profile female, 30;
     extend recommendations with dfTitanic;
     echo value;
     classify to passengerSurvival the profile male, 1st using 30 nns;
     echo value",
    rakuLocation = rakuLocationPath ) )
```

## SMR query

```{r}
smrObj %>% SMRMonGetProperty("properties") %>% SMRMonTakeValue
```

```{r}
ToRecommenderWorkflowCode("show the recommender matrix number of rows")
```
```{r}
ToRecommenderWorkflowCode( 
  "use recommender smrObj2;
     display properties;
     display the tag types;
     show sub matrices", 
  rakuLocation = rakuLocationPath,
  parse = F )
```
```{r}
smrObj <- smrObj %>% SMRMonGetMatrixProperty( property = "properties" ) %>% SMRMonEchoValue
```

```{r}
smrObj <- smrObj %>% SMRMonGetProperty( property = "properties" ) %>% SMRMonEchoValue
```


```{r}
smrObj3 <-
  eval( ToRecommenderWorkflowCode( 
    "use recommender smrObj;
     show recommender matrix properties;
     show recommender matrix property;
     display the tag types;
     show the recommender itemColumnName;
     show the sparse matrix number of rows;
     show the sparse matrix number of columns;
     display the recommender matrix density;
     show the sparse matrix columns;
     filter the recommendation matrix with male, 30, 40;
     show sparse matrix dimensions;
     show the sub-matrix passengerClass columns;
     show the tag type passengerSurvival density",
    rakuLocation = rakuLocationPath) )
```

```{r}
smrObj <- 
  smrObj %>% 
  SMRMonApplyTagTypeWeights( weights = c( "passengerClass" = 2 ), default = 0 ) %>% 
  SMRMonRecommendByProfile( profile = c( "3rd" ), nrecs = 12 ) %>% 
  SMRMonJoinAcross( dfTitanic ) %>% 
  SMRMonEchoValue
```

# Metadata recomemnder making

```{r}
ToRecommenderWorkflowCode( 
    "create using dfTitanic;
     create metadata recommender for passengerClass over the tag types passengerSex and passengerSurvival;
     show the sparse matrix rownames", 
    rakuLocation = rakuLocationPath,
    parse = F ) 
```

```{r}
smrRes <- 
  eval( ToRecommenderWorkflowCode( 
    "create using dfTitanic;
     create metadata recommender for passengerClass;
     show the sparse matrix rownames", 
    rakuLocation = rakuLocationPath,
    parse = T ) )
```

# Search engine queries

```{r}
ToSearchEngineQueryCode('"male" +"30" +"survived"', target = 'R-SMRMon', rakuLocation = rakuLocationPath )
```


```{r}
SMRMonUnit(dfTitanic) %>% 
  SMRMonCreate %>% 
  SMRMonRetrieveByQueryElements( should = c( 'male' ), must = c( '30', 'survived' ), mustNot = NULL ) %>% 
  SMRMonJoinAcross( dfTitanic ) %>% 
  SMRMonTakeValue
```

