---
title: "SMRMon core code generation"
author: Anton Antonov
date: "```r Sys.Date()```"
output: html_notebook
---

# Introduction

The code in this notebook was used to generate the core code of the `SMRMon` monad; see [1].

The R design and implementation follows the design and implementation of `SMRMon` in Mathematica, see [2].

# Code generation

Here we load the State Monad code generation package:

```{r}
library(StateMonadCodeGenerator)
```

```{r}
GenerateStateMonadCode( monadName = "SMRMon", 
                        memberNames = c("M" = "matrix", 
                                        "M01" = "matrix", 
                                        "TagTypeRange" = "data.frame", 
                                        "TagTypes" = "character", 
                                        "ItemColumnName" = "character",
                                        "TagToIndexRules" = "integer", 
                                        "ItemToIndexRules" = "integer",
                                        "Data" = "data.frame"), 
                        monadObjectArgumentName = "smrObj", 
                        outputFile = "SMRMon-core.R")
```


# References

[1] Anton Antonov, 
[State monad code generator](https://github.com/antononcube/R-packages/tree/master/StateMonadCodeGenerator), 
(2019),
[R-packages at GitHub](https://github.com/antononcube/R-packages).

[2] Anton Antonov, 
[Monadic Sparse Matrix Recommender Mathematica package](https://github.com/antononcube/MathematicaForPrediction/blob/master/MonadicProgramming/MonadicSparseMatrixRecommender.m),
(2018),
[MathematicaForPrediction at GitHub](https://github.com/antononcube/MathematicaForPrediction).
