---
title: "Make interfaces"
author: "Anton Antonov"
output: html_notebook
---


# Introduction

```{r}
library(SparseMatrixRecommender)
library(SparseMatrixRecommenderInterfaces)
library(shiny)
library(shinydashboard)
library(DT)
```

# Titanic


```{r}
smrTitanic <- SMRCreate( dfTitanic, 
                         tagTypes = setdiff( colnames(dfTitanic), "id" ), 
                         itemColumnName = "id" )
```


```{r, eval=F}
SMRCreateSearchInterface( itemSMR = smrTitanic, itemData = dfTitanic, itemDataIDColName = "id", searchColName = "id", itemListIDsSplitPattern = " " )
```

```{r}
smat <- smrTitanic$M
# rownames(smat) <- NULL
# colnames(smat) <- NULL
SMRSparseMatrixToTriplets( smat )
```


# Mushroom

```{r}
smrMushroom <- SMRCreate( dfMushroom, 
                          tagTypes = setdiff( colnames(dfMushroom), "id" ), 
                          itemColumnName = "id" )
```

```{r, eval=F}
SMRCreateSearchInterface( itemSMR = smrMushroom, itemData = dfMushroom, itemDataIDColName = "id", searchColName = "id", itemListIDsSplitPattern = "\\W" )
```