---
title: "R Notebook"
output: html_notebook
---

```{r}
library(magrittr)
library(Matrix)
library(SparseMatrixRecommender)
#devtools::load_all()
```

# Create recommender(s)

```{r}
smrTitanic <- SMRCreate( dataRows = dfTitanic)
```

```{r}
smrMushroom <- SMRCreate( dataRows = dfMushroom,  addTagTypesToColumnNamesQ = TRUE)
```

```{r}
smrMushroomGillColor <- SMRCreate( dataRows = dfMushroom[, -1], itemColumnName = "gill.Color" )
```

------

# Long form

```{r}
SMRMatricesToLongForm(smrTitanic)
```

------

# Wide form

```{r}
SMRMatricesToWideForm( smr = smrTitanic )
```

```{r}
Summary(SMRMatricesToWideForm( smr = smrMushroomGillColor ), maxsum = 12)
```

------

# To metadata recommender (Titanic)

```{r}
SMRSparseMatrixToTriplets(smrTitanic$M)
```

## By matrix product

```{r}
smrAge <- SMRToMetadataRecommender( smr = smrTitanic, tagTypeTo = "passengerAge", tagTypes = NULL )
```

```{r}
smrAge
```

```{r}
xtabs( ~ passengerAge + passengerSex, dfTitanic)
```

## By replacement

```{r}
smrAge <- SMRToMetadataRecommenderByReplacement( smr = smrTitanic, tagTypeTo = "passengerAge", tagTypes = NULL, tagSelection = function(x) c( TRUE, rep_len(x = FALSE, length.out = length(x)-1 )), addTagTypesToColumnNamesQ = TRUE )
```

```{r}
smrAge2 <- SMRToMetadataRecommenderByReplacement( smr = smrTitanic, tagTypeTo = "passengerAge", tagTypes = NULL, tagSelection = 3, addTagTypesToColumnNamesQ = TRUE )
```

```{r}
smrAge3 <- SMRToMetadataRecommenderByReplacement( smr = smrTitanic, tagTypeTo = "passengerAge", tagTypes = NULL, nTopTags = 3, tagSelection = 3, addTagTypesToColumnNamesQ = TRUE )
```

```{r}
as.matrix(smrAge$M)
```

```{r}
as.matrix(smrAge2$M)
```


```{r}
as.matrix(smrAge3$M)
```

------

# To metadata recommender (Mushroom)

## By matrix product

```{r}
smrGillColor1 <- SMRToMetadataRecommender( smr = smrMushroom, tagTypeTo = "odor", tagTypes = NULL, normalizerFunc = "Cosine" )
```


```{r}
as.matrix(smrGillColor1$M)[, grepl("ring", colnames(smrGillColor1$M))]
```
```{r}
xtabs( ~ odor + ring.Type, dfMushroom)
```

## By replacement

```{r}
smrGillColor1 <- SMRToMetadataRecommenderByReplacement( smr = smrMushroomGillColor, tagTypeTo = "odor", tagTypes = NULL, nTopTags = 4 )
smrGillColor2 <- SMRToMetadataRecommenderByReplacement( smr = smrMushroomGillColor, tagTypeTo = "odor", tagTypes = NULL, nTopTags = 4 )
```

```{r}
xtabs( ~ gill.Color + ring.Type, dfMushroom)
```

```{r}
xtabs( ~ odor + ring.Type, dfMushroom)
```

```{r}
as.matrix(smrGillColor1$M)[, grepl("ring", colnames(smrGillColor1$M))]
```

```{r}
as.matrix(smrGillColor2$M)
```

# Unitize matrices

```{r}
smrFreq <- SMRUnitizeSubMatrices( smr = smrTitanic, tol = 0.1 )
```

```{r}
colSums(smrFreq$M)
```

```{r}
summary(smrFreq$M@x)
```

# SMR matrix to data frame

```{r}
SMRSparseMatrixToDataFrame( smrTitanic, tagType = "passengerAge" )
```

