---
title: "LSAMon workflows by natural commands"
author: Anton Antonov
date: "```r Sys.Date()```"
output: html_notebook
---

```{r}
library(LSAMon)
library(Matrix)
library(magrittr)
library(ExternalParsersHookUp)
library(MathematicaVsRData)
```

# Introduction

This notebooks demonstrates the construction of recommender workflows
using natural language commands.

# Creation

Simple creation:

```{r}
lsaObj <-
  LSAMonUnit( documents = textHamlet ) %>%
  LSAMonMakeDocumentTermMatrix()
```

# Additional definitions

```{r, eval=T}
Perl6LSAMonParsingLib <- function() {
    file.path("/", "Volumes", "Macintosh HD", "Users", "antonov", "ConversationalAgents", "Packages", "Perl6", "LatentSemanticAnalysisWorkflows", "lib")
}
```

```{r}
file.exists(Perl6LSAMonParsingLib())
```

```{r, eval=T}
to_LSAMon_R_command <- function(command, parse=TRUE) {
  pres <- Perl6Command( command = paste0( "say to_LSAMon_R(\"", command, "\")"),
                        moduleDirectory = Perl6LSAMonParsingLib(),
                        moduleName = "LatentSemanticAnalysisWorkflows" )
  messageInds <- grep( "^Possible", pres )
  if( length(messageInds) > 0 ) {
    messageLines <- pres[messageInds]
    print(messageLines)
    pres <- pres[setdiff(1:length(pres), messageInds)]
  }
  pres <- gsub( "\\\"", "\"", pres, fixed = T)
  if(parse) { parse(text = pres) }
  else { pres }
}
```

# Basic pipeline

```{r}
textHamlet
```

```{r}
smrObj2 <-
  eval( expr = to_LSAMon_R_command( 
  "create from textHamlet;
   make document term matrix with stemming FALSE and automatic stop words;
   apply lsi functions global weight function idf, local term weight function none, normalizer function cosine;
   extract 12 topics using method NNMF and max steps 12;
   show topics table with 12 columns and 10 terms;
   show thesaurus table for king, castle, denmark;" ) )
```

```{r}
to_LSAMon_R_command( 
  "create from textHamlet;
   make document term matrix with stemming FALSE and automatic stop words;
   apply lsi functions global weight function idf, local term weight function none, normalizer function cosine;
   extract 12 topics using method NNMF and max steps 12;
   show topics table with 12 columns and 10 terms;
   show thesaurus table for king, castle, denmark;", parse = FALSE  )
```

