---
title: "Topics extraction for USA presidential speeches"
author: "Anton Antonov"
date: 2019-04-02
output: html_notebook
---

```{r}
library(LSAMon)
library(magrittr)
library(Matrix)
library(stopwords)
library(lattice)
library(OutlierIdentifiers)
library(MathematicaVsRData)
```

```{r}
method <- "NNMF"
maxSteps <- if( method == "NNMF") { 20 } else { NULL }
numberOfTopics <- 60
minNumberOfDocumentsPerTerm <- 25
```

# Introduction

# Topic extraction


```{r}
texts <- dfUSAPresidentsSpeeches$Text
texts <- setNames(texts, paste( formatC( 1:length(texts), width = 6, flag = "0" ), dfUSAPresidentsSpeeches$Name, sep = "-") )
```

```{r}
names(texts)[1:12]
```

```{r}
lsaObj <-
  LSAMonUnit( tolower(dfUSAPresidentsSpeeches$Text) ) %>% 
  LSAMonMakeDocumentTermMatrix( stopWords = stopwords::stopwords() )
```

```{r}
docTermMat <- lsaObj %>% LSAMonTakeDocumentTermMatrix
dim(docTermMat)
```


Fill-in:

```{r}
length(docTermMat@x)/length(docTermMat)
```

```{r}
summary(docTermMat@x)
```

```{r}
lsaObj <-
  LSAMonUnit( texts ) %>% 
  LSAMonMakeDocumentTermMatrix( stemWordsQ = FALSE, stopWords = stopwords::stopwords() ) %>% 
  LSAMonApplyTermWeightFunctions( globalWeightFunction = "IDF", localWeightFunction = "TermFrequency", normalizerFunction = "Cosine" ) %>% 
  LSAMonExtractTopics( numberOfTopics = numberOfTopics, minNumberOfDocumentsPerTerm = minNumberOfDocumentsPerTerm, maxSteps = maxSteps, method = method ) %>% 
  LSAMonEchoTopicsTable( numberOfTerms = 12 )
```

```{r}
plot(ParetoPrincipleAdherence::ParetoForNumericalVector( data = log(nrow(docTermMat)) -log(colSums(docTermMat) )))
```

```{r}
cs <- rep(1,10000)
cs <- rev(sort(cs))
cs <- cumsum(cs) / sum(cs)
plot(cs)
```

```{r}
ParetoPrincipleAdherence::ParetoPlot( data = colSums(docTermMat) )
```


# The extracted topics

```{r}
lsaObj <-
  lsaObj %>% 
  LSAMonInterpretBasisVectors( n = 20 )
dfTopics <- lsaObj %>% LSAMonTakeValue
```

```{r}
res <- dfTopics %>% dplyr::filter( TopicRank == 12 ) %>% dplyr::select( TermCoefficient )
OutlierPosition(res$TermCoefficient, SPLUSQuartileIdentifierParameters)
```

```{r}
dfTopics %>% dplyr::filter(TopicRank == 3 )
```


```{r}
sFactorsDF <- dfTopics %>% dplyr::select( TopicRank, TopicSignificanceFactor ) %>% unique()
lattice::xyplot( TopicSignificanceFactor ~ TopicRank, sFactorsDF )
```

```{r}
dfTopicsWideForm <- 
  reshape2::dcast( data = dfTopics, formula = TermRank ~ TopicName, value.var = "Term" )
dfTopicsWideForm
```

```{r}
lsaObj %>% LSAMonTakeTopicNames
```


```{r}
pairs <- expand.grid( names(dfTopicsWideForm), names(dfTopicsWideForm), stringsAsFactors = F)
res <- purrr::map2_dbl( pairs$Var1, pairs$Var2,
                        function(x,y) { 
                          if( x == y ) { 0 } else { length(intersect( dfTopicsWideForm[[x]], dfTopicsWideForm[[y]] ) ) } 
                        })
qMat <- matrix(res, nrow = ncol(dfTopicsWideForm) )
rownames(qMat) <- colnames(dfTopicsWideForm)
colnames(qMat) <- colnames(dfTopicsWideForm)
d3heatmap::d3heatmap(qMat, Rowv = F, Colv = F, scale = "none", colors = "Blues")
```

```{r}
summary(as.numeric(qMat))
```

## Statistical thesaurus extraction


```{r}
lsaObj <-
  lsaObj %>% 
  LSAMonExtractStatisticalThesaurus( searchWords = sort(c("king", "sword", "god", "economy", "health", "poison", "war", "iraq")) )
nnsDF <- dplyr::bind_rows( lsaObj %>% LSAMonTakeValue )
nnsDF
```


```{r}
nnsDF2 <- 
  nnsDF %>% 
  dplyr::group_by( SearchTerm ) %>% 
  dplyr::arrange( Word.Distance ) %>% 
  dplyr::mutate( Rank = dplyr::row_number()) %>% 
  dplyr::select( SearchTerm, Rank, Word.Word )
reshape2::dcast( formula = SearchTerm ~ Rank, data = nnsDF2, value.var = "Word.Word" )
```

# Topics representation

### W matrix

```{r, eval=F}
d3heatmap::d3heatmap( lsaObj %>% LSAMonTakeW, scale = "row", colors = "Blues" )
```

```{r, eval=F}
qMat <- (lsaObj %>% LSAMonTakeW) %*% t(lsaObj %>% LSAMonTakeW)
d3heatmap::d3heatmap( qMat, colors = "Blues" )
```

### Free text representation

```{r}
lsaObj %>% 
  LSAMonRepresentByTopics( query = "Unites States military forces bombed Vietnam.") %>% 
  LSAMonTakeValue
```

### Representation

```{r}
summary((lsaObj %>% LSAMonTakeW)@x)
```

```{r}
if(TRUE) {
  tags <- purrr::map_chr( strsplit( rownames(lsaObj %>% LSAMonTakeW), "-"), function(x) x[[2]])
  uniqueTags <- unique(tags)
  tags <- setNames( tags, rownames(lsaObj %>% LSAMonTakeW) )
} else {
  tags <- 1:nrow( lsaObj %>% LSAMonTakeW )
  tags <- tags %/% 5
  #tags <- setNames( tags, rownames(lsaObj %>% LSAMonTakeW) )
  tags
}
```

```{r}
lsaObj2 <- lsaObj %>% LSAMonRepresentDocumentTagsByTopics( tags = tags, minThreshold = 0.005 )
qMat <- as.matrix(lsaObj2 %>% LSAMonTakeValue)
qMat <- qMat[ uniqueTags, ]
d3heatmap::d3heatmap( qMat, Rowv = FALSE, Colv = TRUE, scale = "row", colors = "Blues" )
```


```{r}
dfTopicsWideForm
```



