---
title: "Package data preparation"
author: Anton Antonov
date: 2020-12-29
output: html_notebook
---

# Ingest word data

```{r}
dfEnglishWords <- read.csv( file = "../inst/extdata/dfEnglishWords.csv", stringsAsFactors = FALSE)
```

```{r}
dim(dfEnglishWords)
```

```{r}
summary(as.data.frame(unclass(dfEnglishWords), stringsAsFactors = TRUE))
```

```{r}
dfEnglishWords$KnownWordQ <- ifelse( dfEnglishWords$KnownWordQ == "True", TRUE, FALSE)
dfEnglishWords$CommonWordQ <- ifelse( dfEnglishWords$CommonWordQ == "True", TRUE, FALSE)
dfEnglishWords$StopWordQ <- ifelse( dfEnglishWords$StopWordQ == "True", TRUE, FALSE)
```

```{r}
summary(dfEnglishWords)
```


# Ingest pet names data

```{r}
dfPetNameCounts <- read.csv( file = "../inst/extdata/dfPetNameCounts.csv", stringsAsFactors = FALSE)
```

```{r}
dfPetNameCounts$Name <- gsub( '\"', '\'', dfPetNameCounts$Name, fixed = F) 
sum(grepl( '\"', dfPetNameCounts$Name, fixed= T))
sum(grepl( "'", dfPetNameCounts$Name, fixed= T))
```

```{r}
Summary(dfPetNameCounts)
```


# Pretentious job titles

```{r}
aPretentiousJobTitleWords <-
  list(
    "english" =
      list(
        "uno" = c("Lead", "Senior", "Direct", "Corporate", "Dynamic",
                  "Future", "Product", "National", "Regional", "District",
                  "Central", "Global", "Relational", "Customer", "Investor",
                  "Dynamic", "International", "Legacy", "Forward", "Interactive",
                  "Internal", "Human", "Chief", "Principal"),
        "zwei" = c("Solutions", "Program", "Brand", "Security", "Research",
                   "Marketing", "Directives", "Implementation", "Integration",
                   "Functionality", "Response", "Paradigm", "Tactics", "Identity",
                   "Markets", "Group", "Resonance", "Applications", "Optimization",
                   "Operations", "Infrastructure", "Intranet", "Communications",
                   "Web", "Branding", "Quality", "Assurance", "Impact", "Mobility",
                   "Ideation", "Data", "Creative", "Configuration",
                   "Accountability", "Interactions", "Factors", "Usability",
                   "Metrics", "Team"),
        "trois" = c("Supervisor", "Associate", "Executive", "Liason",
                    "Officer", "Manager", "Engineer", "Specialist", "Director",
                    "Coordinator", "Administrator", "Architect", "Analyst",
                    "Designer", "Planner", "Synergist", "Orchestrator", "Technician",
                    "Developer", "Producer", "Consultant", "Assistant",
                    "Facilitator", "Agent", "Representative", "Strategist")
      ),
    "bulgarian" =
      list(
        "uno" = c("Бъдещ", "Водещ", "Главен", "Старши", "Човешки", "Вътрешен",
          "Глобален", "Директен", "Клиентов", "Областен", "Динамичен",
          "Динамичен", "Централен", "Инвестиращ", "Национален", "Регионален",
          "Релационен", "Наследствен", "Прогресивен", "Интерактивен",
          "Корпоративен", "Международен", "Продукционен"),
        "zwei" = c("Идеи", "Групи", "Данни", "Екипи", "Марки", "Мрежи",
          "Пазари", "Отговори", "Решения", "Тактики", "Фактори", "Интранет",
          "Качество", "Операции", "Програми", "Директиви", "Маркетинг",
          "Мобилност", "Отчетност", "Парадигми", "Прилагане", "Резонанси",
          "Сигурност", "Брандиране", "Интеграция", "Показатели", "Приложения",
          "Въздействие", "Идентичност", "Изследвания", "Комуникации",
          "Креативност", "Оптимизация", "Осигуряване", "Конфигурации",
          "Използваемост", "Взаимодействия", "Функционалности",
          "Инфраструктурата"),
        "trois" = c("Агент", "Плановик", "Техник", "Инженер", "Стратег",
          "Архитект", "Асистент", "Дизайнер", "Директор", "Мениджър",
          "Началник", "Служител", "Посредник", "Продуцент", "Синергист",
          "Сътрудник", "Анализатор", "Изпълнител", "Консултант", "Специалист",
          "Координатор", "Оркестратор", "Разработчик", "Супервайзор",
          "Фасилитатор", "Представител", "Проектант", "Администратор")
        )
    )
```

# Make the data

```{r, eval=F}
usethis::use_data(dfEnglishWords)
```


```{r, eval=F}
usethis::use_data(dfPetNameCounts, overwrite = T)
```


```{r, eval=F}
usethis::use_data(aPretentiousJobTitleWords, overwrite = T)
```
