---
title: "RandomDataFrame experiments"
author: Anton Antonov
date: 2020-12-28
output: html_notebook
---

```{r}
devtools::load_all()
library(tidyverse)
```

# First experiments

```{r}
RandomString(6, lambda = 8)
```

```{r}
RandomWord(6, "Common")
```

# Column names

```{r}
dfRand <- RandomDataFrame( nrow = 20, ncol = 3, generators = list( c("a", "b", "c"), 1:12 ))
dfRand
```

```{r, rows.print = 50 }
dfRand <- RandomDataFrame( nrow = 20, ncol = 3, generators = list( c("a", "b", "c"), 1:12, rnorm ))
dfRand[ do.call( order, dfRand), ]
```

```{r}
RandomDataFrame( nrow = 4, ncol = 5, columnNames = c("a", "b", "c"))
```

```{r}
RandomDataFrame( nrow = 4, ncol = 5, columnNamesGenerator = RandomWord )
```

```{r}
RandomDataFrame( nrow = 4, ncol = 5, columnNamesGenerator = function(k) RandomWord(k, "Common") )
```

```{r}
RandomDataFrame( nrow = 4, ncol = 5, columnNamesGenerator = function(k) rpois(k, lambda = 5) )
```

# Min and max number of values

```{r}
RandomDataFrame( nrow = 4, ncol = 5, minNumberOfValues = NULL, maxNumberOfValues = 18, rowNamesQ = T)
```
# Generators

```{r}
dfGen1 <- RandomDataFrame( nrow = 100, columnNames = c("a", "b", "c", "d"), generators = list( "b" = rnorm, "d" = RandomString ) )
dfGen1
```

```{r}
mean(dfGen1$b)
sd(dfGen1$b)
ExcessCurtosis <- function(x, k) { mean( (x - mean(x) )^4 ) - 3 * mean( (x - mean(x) )^2 )^2 }
ExcessCurtosis( dfGen1$b )
```

```{r}
RandomDataFrame( nrow = 4, ncol = 5, generators = function(k) rnorm( n = k, mean = 40, sd = 3) )
```

```{r}
RandomDataFrame( nrow = 4, ncol = 5, generators = c( function(k) rpois( n = k, lambda = 4), function(k) RandomWord(k) ))
```

# Form

```{r, rows.print = 30}
dfRes <- RandomDataFrame( nrow = 4, columnNames = c("word", "date", "rand"), form = "long", generators = c( "word" = RandomWord, "date" = RandomDate, "rand" = runif), rowNamesQ = F )
dfRes
```

```{r,  rows.print = 30}
dfResWide <- dfRes %>% tidyr::pivot_wider( id_cols = "ID", names_from = "Variable", values_from = colnames(dfRes)[3:ncol(dfRes)])
dfResWide <- dfResWide[, purrr::map_lgl( dfResWide, function(x) sum(is.na(x)) < 1)]
dfResWide
```

# Batch execution

```{r}
lsRDFs <- purrr::map( 1:50, ~ RandomDataFrame( columnNamesGenerator = NA) )
```

```{r, rows.print = 40}
purrr::map_dfr( lsRDFs, ~ c( NRow = nrow(.), NCol = ncol(.) ) ) %>% dplyr::arrange(desc(NRow * NCol))
```

```{r}
RandomWord(5)
```

# Insufficient values


```{r}
RandomDataFrame( 
  nrow = 6, 
  columnNames = c("ID", "Text"), 
  generators = 
    list( 1:10, function(n) purrr::map_chr( 1:n, ~ paste(RandomWord(runif(1,2,4)), collapse = " " )) )
)
```

```{r, rows.print=30}
RandomDataFrame( 
  nrow = 3, 
  columnNames = c("ID", "Text"), 
  generators = 
    list( 1:10, function(n) purrr::map_chr( 1:n, ~ paste(sample(c("java", "javascript", "ide", "agile"), 3, replace = T), collapse = " " )) )
)
```

```{r}
RandomDataFrame( 
  nrow = 12, 
  columnNames = c("ID", "Text"), 
  generators = 
    list( 1:10, function(n) RandomWord(4))
)
```

