---
title: "RSTMon core code generation"
author: Anton Antonov
date: "```r Sys.Date()```"
output: html_notebook
---

# Introduction

The code in this notebook was used to generate the core code of the `RSTMon` monad; see [1].

The monad is part of the R-package "RecommenderTestFunctions", [2].

# Code generation

Here we load the State Monad code generation package:

```{r}
library(StateMonadCodeGenerator)
```

```{r}
GenerateStateMonadCode( monadName = "RSTMon", 
                        memberNames = c("SMR" = "list", 
                                        "ProfileTagTypes"    = "character",
                                        "LabelTagType"       = "character", 
                                        "NTopLabels"         = "integer",
                                        "NTopRecs"           = "integer",
                                        "FreqSetMinSupport"  = "numeric", 
                                        "FreqSetMinCount"    = "integer",
                                        "FreqSetsMinLen"     = "integer",
                                        "FreqSetsMaxLen"     = "integer",
                                        "Itemsets"           = "data.frame"
                                        ), 
                        monadObjectArgumentName = "rstObj", 
                        outputFile = "RSTMon-core.R")
```


# References

[1] Anton Antonov, 
[State monad code generator](https://github.com/antononcube/R-packages/tree/master/StateMonadCodeGenerator), 
(2019),
[R-packages at GitHub](https://github.com/antononcube/R-packages).

[2] Anton Antonov,
[Recommender Test Functions](https://github.com/antononcube/R-packages/tree/master/RecommenderTestFunctions),
(2020),
[R-packages at GitHub](https://github.com/antononcube/R-packages).
